# Generated by Django 3.2.16 on 2022-12-19 11:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('creation_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 19, 17, 23, 10, 982534))),
                ('last_login', models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 19, 17, 23, 10, 982534))),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('user_name', models.CharField(blank=True, max_length=30, null=True)),
                ('user_pass', models.CharField(blank=True, max_length=30, null=True)),
                ('institution_id', models.CharField(max_length=30, null=True)),
                ('verified', models.BooleanField(blank=True, default=0)),
                ('user_id', models.CharField(max_length=100, null=True)),
                ('auth_token', models.CharField(max_length=255, null=True)),
                ('acc_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user')),
            ],
        ),
    ]
