# Generated by Django 3.2.16 on 2022-12-19 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 19, 17, 23, 23, 75108)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 19, 17, 23, 23, 75108)),
        ),
    ]
