# Generated by Django 3.2.16 on 2022-12-20 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221219_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 20, 15, 42, 14, 492385)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 20, 15, 42, 14, 492385)),
        ),
    ]
