# Generated by Django 3.2.16 on 2022-12-20 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20221220_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 20, 16, 23, 6, 871592)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 20, 16, 23, 6, 871592)),
        ),
    ]
