# Generated by Django 3.2.16 on 2022-12-20 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20221220_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 20, 16, 25, 29, 67936)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 20, 16, 25, 29, 68934)),
        ),
    ]
